# Use an official Node.js runtime as base image
FROM node:18-alpine

EXPOSE 3001

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the project's dependencies
RUN npm install

# Copy the rest of the project files to the container
COPY . .

# Build the project for production
RUN npm run build

# Set the command to start the server in the container
CMD ["npm", "start"]
